import datetime
from decimal import Decimal

BORROWERS = {'B-DEMO-001': {'id': 'B-DEMO-001',
                'alias': 'Demo Farmer 001',
                'district': 'Nashik',
                'branch': 'Nashik Rural',
                'crop': 'Wheat',
                'area_ha': 2.4,
                'irrigation_fraction': 0.45,
                'land_class': 'smallholder',
                'synthetic': True,
                'sowing_date': datetime.date(2026, 6, 20),
                'harvest_date': datetime.date(2026, 11, 1),
                'loan_principal_inr': Decimal('120000'),
                'annual_rate': Decimal('0.12'),
                'disbursed_at': datetime.date(2026, 6, 22),
                'due_at': datetime.date(2026, 11, 5),
                'initial_cash_inr': Decimal('18000'),
                'input_cost_inr': Decimal('53000'),
                'living_cost_inr': Decimal('12000'),
                'yield_t_per_ha': Decimal('3.2'),
                'price_inr_per_quintal': Decimal('2450'),
                'sale_fraction': Decimal('0.92'),
                'credit_history': [{'season': '2023/24',
                                    'status': 'on_time',
                                    'source_status': 'synthetic_demo_record'},
                                   {'season': '2024/25',
                                    'status': 'on_time',
                                    'source_status': 'synthetic_demo_record'}]},
 'B-DEMO-002': {'id': 'B-DEMO-002',
                'alias': 'Demo Farmer 002',
                'district': 'Pune',
                'branch': 'Pune Rural',
                'crop': 'Maize',
                'area_ha': 1.8,
                'irrigation_fraction': 0.25,
                'land_class': 'smallholder',
                'synthetic': True,
                'sowing_date': datetime.date(2026, 6, 15),
                'harvest_date': datetime.date(2026, 11, 2),
                'loan_principal_inr': Decimal('90000'),
                'annual_rate': Decimal('0.11'),
                'disbursed_at': datetime.date(2026, 6, 18),
                'due_at': datetime.date(2026, 11, 8),
                'initial_cash_inr': Decimal('12000'),
                'input_cost_inr': Decimal('41000'),
                'living_cost_inr': Decimal('10000'),
                'yield_t_per_ha': Decimal('4.1'),
                'price_inr_per_quintal': Decimal('2100'),
                'sale_fraction': Decimal('0.9'),
                'credit_history': [{'season': '2023/24',
                                    'status': 'unknown',
                                    'source_status': 'synthetic_demo_record'}]}}
