import { useEffect, useState } from 'react'
import { AlertTriangle, Calculator, History, WalletCards } from 'lucide-react'

const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000'
const inr=(value:unknown)=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`

export function PortfolioAllocatorPage(){
  const [budget,setBudget]=useState('50000'),[support,setSupport]=useState('25000'),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10))
  const [result,setResult]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const loadHistory=()=>fetch(`${API}/api/portfolio/allocations`).then(r=>{if(!r.ok)throw new Error('Allocation history unavailable');return r.json()}).then(body=>setHistory(body.allocations||[])).catch(e=>setError(e.message))
  useEffect(()=>{loadHistory()},[])
  const allocate=async()=>{setBusy(true);setError('');try{const response=await fetch(`${API}/api/portfolio/allocate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({budget_inr:budget,support_amount_inr:support,as_of:asOf})});const body=await response.json();if(!response.ok)throw new Error(body.detail||'Allocation could not be calculated');setResult(body);await loadHistory()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <div className="content-grid"><section className="card wide"><div className="section-title"><div><h2>Demo portfolio budget allocator</h2><p>Rank synthetic borrowers by the modeled due-date gap relative to principal, then allocate a fixed support amount without exceeding the entered budget.</p></div><span className="tag amber">SIMULATION ONLY</span></div>
    <div className="toolbar" style={{alignItems:'end',flexWrap:'wrap'}}><label className="control-label"><span>Total budget (INR)</span><input type="number" min="1" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label className="control-label"><span>Support per selected borrower (INR)</span><input type="number" min="1" step="0.01" value={support} onChange={e=>setSupport(e.target.value)}/></label><label className="control-label"><span>Assessment date</span><input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><button className="btn-primary" onClick={allocate} disabled={busy||!budget||!support}><Calculator size={15}/>{busy?'Calculating…':'Allocate budget'}</button></div>
    {error&&<div className="error-banner"><AlertTriangle size={16}/>{error}</div>}
    {result&&<><div className="kpi-grid"><div className="kpi"><small>Budget</small><strong>{inr(result.budget_inr)}</strong></div><div className="kpi"><small>Allocated</small><strong>{inr(result.allocated_inr)}</strong></div><div className="kpi"><small>Remaining</small><strong>{inr(result.remaining_budget_inr)}</strong></div><div className="kpi"><small>Budget invariant</small><strong>{result.budget_invariant_holds?'Holds':'Failed'}</strong></div></div><div className="notice amber"><AlertTriangle size={17}/><div><b>Recommendation only</b><span> This allocator uses synthetic finance and illustrative scenarios. It does not transfer funds, modify a loan, or estimate real default risk. Policy: {result.policy_version}.</span></div></div><div className="table-wrap"><table><thead><tr><th>Rank / borrower</th><th>Modeled gap</th><th>Gap / principal</th><th>Warnings</th><th>Allocation</th><th>Reason</th></tr></thead><tbody>{result.candidates.map((row:any,index:number)=><tr key={row.borrower_id}><td><b>#{index+1} {row.alias}</b><small>{row.borrower_id} · scenario {row.scenario_id}</small></td><td>{inr(row.modeled_gap_inr)}</td><td>{(Number(row.priority_score)*100).toFixed(2)}%</td><td>{row.warning_count}</td><td><span className={`tag ${row.selected?'green':'neutral'}`}>{row.selected?inr(row.support_amount_inr):'Not selected'}</span></td><td>{row.reason}</td></tr>)}</tbody></table></div></>}
  </section><section className="card wide"><div className="section-title"><div><h2>Saved allocation runs</h2><p>Each run stores its policy version, as-of date, budget and candidate scenario IDs.</p></div><History size={18}/></div>{history.length?<div className="table-wrap"><table><thead><tr><th>Run</th><th>Created</th><th>As of</th><th>Allocated / budget</th><th>Policy</th></tr></thead><tbody>{history.map(row=><tr key={row.allocation_id}><td><b>{row.allocation_id}</b></td><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.as_of}</td><td>{inr(row.allocated_inr)} / {inr(row.budget_inr)}</td><td>{row.policy_version}</td></tr>)}</tbody></table></div>:<div className="empty"><WalletCards size={18}/> No allocation runs have been saved.</div>}</section></div>
}
